version: "3.7"

services:
    consumer-webhook-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: consumer-webhook-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        extra_hosts:
            - "host.docker.internal:172.17.0.1"

    nginx-consumer-webhook-app:
        image: nginx:alpine
        container_name: nginx-consumer-webhook-app
        ports:
            - "81:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        extra_hosts:
            - "host.docker.internal:172.17.0.1"
